Revert "Reformat souce code"

diff --git a/src/utils/mp_gpprof_server/libraries/fcgi-2.4.0/install-sh b/src/utils/mp_gpprof_server/libraries/fcgi-2.4.0/install-sh
--- a/src/utils/mp_gpprof_server/libraries/fcgi-2.4.0/install-sh
+++ b/src/utils/mp_gpprof_server/libraries/fcgi-2.4.0/install-sh
@@ -1,44 +1,60 @@
-#!/ bin / sh
+#!/bin/sh
 #
-#install - install a program, script, or datafile
-#This comes from X11R5(mit / util / scripts / install.sh).
+# install - install a program, script, or datafile
+# This comes from X11R5 (mit/util/scripts/install.sh).
 #
-#Copyright 1991 by the Massachusetts Institute of Technology
+# Copyright 1991 by the Massachusetts Institute of Technology
 #
-#Permission to use, copy, modify, distribute, and sell this software and its
-#documentation for any purpose is hereby granted without fee, provided that
-#the above copyright notice appear in all copies and that both that
-#copyright notice and this permission notice appear in supporting
-#documentation, and that the name of M.I.T.not be used in advertising or
-#publicity pertaining to distribution of the software without specific,
-#written prior permission.M.I.T.makes no representations about the
-#suitability of this software for any purpose.It is provided "as is"
-#without express or implied warranty.
+# Permission to use, copy, modify, distribute, and sell this software and its
+# documentation for any purpose is hereby granted without fee, provided that
+# the above copyright notice appear in all copies and that both that
+# copyright notice and this permission notice appear in supporting
+# documentation, and that the name of M.I.T. not be used in advertising or
+# publicity pertaining to distribution of the software without specific,
+# written prior permission.  M.I.T. makes no representations about the
+# suitability of this software for any purpose.  It is provided "as is"
+# without express or implied warranty.
 #
-#Calling this script install - sh is preferred over install.sh, to prevent
+# Calling this script install-sh is preferred over install.sh, to prevent
 # `make' implicit rules from creating a file called install from it
-#when there is no Makefile.
+# when there is no Makefile.
 #
-#This script is compatible with the BSD install script, but was written
-#from scratch.It can only install one file at a time, a restriction
-#shared with many OS's install programs.
+# This script is compatible with the BSD install script, but was written
+# from scratch.  It can only install one file at a time, a restriction
+# shared with many OS's install programs.
 
-#set DOITPROG to echo to test this script
 
-#Don 't use :- since 4.3BSD and earlier shells don' t like it.
-doit = "${DOITPROG-}"
+# set DOITPROG to echo to test this script
 
-#put in absolute paths if you don't have them in your path; or use env. vars.
+# Don't use :- since 4.3BSD and earlier shells don't like it.
+doit="${DOITPROG-}"
 
-    mvprog = "${MVPROG-mv}" cpprog = "${CPPROG-cp}" chmodprog = "${CHMODPROG-chmod}" chownprog =
-        "${CHOWNPROG-chown}" chgrpprog = "${CHGRPPROG-chgrp}" stripprog = "${STRIPPROG-strip}" rmprog =
-            "${RMPROG-rm}" mkdirprog = "${MKDIRPROG-mkdir}"
 
-    transformbasename = "" transform_arg = "" instcmd = "$mvprog" chmodcmd = "$chmodprog 0755" chowncmd = "" chgrpcmd =
-        "" stripcmd = "" rmcmd = "$rmprog -f" mvcmd = "$mvprog" src = "" dst = "" dir_arg = ""
+# put in absolute paths if you don't have them in your path; or use env. vars.
 
-    while[x "$1" != x];
-do
+mvprog="${MVPROG-mv}"
+cpprog="${CPPROG-cp}"
+chmodprog="${CHMODPROG-chmod}"
+chownprog="${CHOWNPROG-chown}"
+chgrpprog="${CHGRPPROG-chgrp}"
+stripprog="${STRIPPROG-strip}"
+rmprog="${RMPROG-rm}"
+mkdirprog="${MKDIRPROG-mkdir}"
+
+transformbasename=""
+transform_arg=""
+instcmd="$mvprog"
+chmodcmd="$chmodprog 0755"
+chowncmd=""
+chgrpcmd=""
+stripcmd=""
+rmcmd="$rmprog -f"
+mvcmd="$mvprog"
+src=""
+dst=""
+dir_arg=""
+
+while [ x"$1" != x ]; do
     case $1 in
 	-c) instcmd="$cpprog"
 	    shift
@@ -79,121 +95,157 @@ do
 	    then
 		src=$1
 	    else
-#this colon is to work around a 386BSD / bin / sh bug
+		# this colon is to work around a 386BSD /bin/sh bug
 		:
-        dst = $1 fi shift continue;
-    ;
-    esac done
+		dst=$1
+	    fi
+	    shift
+	    continue;;
+    esac
+done
 
-        if[x "$src" = x] then echo "install:	no input file specified" exit 1 else true fi
+if [ x"$src" = x ]
+then
+	echo "install:	no input file specified"
+	exit 1
+else
+	true
+fi
 
-        if[x "$dir_arg" != x];
-    then dst = $src src = ""
+if [ x"$dir_arg" != x ]; then
+	dst=$src
+	src=""
+	
+	if [ -d $dst ]; then
+		instcmd=:
+		chmodcmd=""
+	else
+		instcmd=mkdir
+	fi
+else
 
-        if[-d $dst];
-    then instcmd = : chmodcmd = "" else instcmd = mkdir fi else
+# Waiting for this to be detected by the "$instcmd $src $dsttmp" command
+# might cause directories to be created, which would be especially bad 
+# if $src (and thus $dsttmp) contains '*'.
 
-#Waiting for this to be detected by the "$instcmd $src $dsttmp" command
-#might cause directories to be created, which would be especially bad
-#if $src(and thus $dsttmp) contains '*'.
+	if [ -f $src -o -d $src ]
+	then
+		true
+	else
+		echo "install:  $src does not exist"
+		exit 1
+	fi
+	
+	if [ x"$dst" = x ]
+	then
+		echo "install:	no destination specified"
+		exit 1
+	else
+		true
+	fi
 
-                     if[-f $src - o - d $src] then true else echo "install:  $src does not exist" exit 1 fi
+# If destination is a directory, append the input filename; if your system
+# does not like double slashes in filenames, you may need to add some logic
 
-                     if[x "$dst" = x] then echo "install:	no destination specified" exit 1 else true fi
+	if [ -d $dst ]
+	then
+		dst="$dst"/`basename $src`
+	else
+		true
+	fi
+fi
 
-#If destination is a directory, append the input filename; if your system
-#does not like double slashes in filenames, you may need to add some logic
+## this sed command emulates the dirname command
+dstdir=`echo $dst | sed -e 's,[^/]*$,,;s,/$,,;s,^$,.,'`
 
-                     if[-d $dst] then dst =
-                         "$dst" /`basename $src` else true fi fi
+# Make sure that the destination directory exists.
+#  this part is taken from Noah Friedman's mkinstalldirs script
 
-                         ##this sed command emulates the dirname command dstdir =`echo $dst |
-                                                                                 sed - e 's,[^/]*$,,;s,/$,,;s,^$,.,'`
+# Skip lots of stat calls in the usual case.
+if [ ! -d "$dstdir" ]; then
+defaultIFS='	
+'
+IFS="${IFS-${defaultIFS}}"
 
-#Make sure that the destination directory exists.
-#this part is taken from Noah Friedman's mkinstalldirs script
+oIFS="${IFS}"
+# Some sh's can't handle IFS=/ for some reason.
+IFS='%'
+set - `echo ${dstdir} | sed -e 's@/@%@g' -e 's@^%@/@'`
+IFS="${oIFS}"
 
-#Skip lots of stat calls in the usual case.
-                                                                                     if[! - d "$dstdir"];
-    then defaultIFS ='	
-' IFS = "${IFS-${defaultIFS}}"
+pathcomp=''
 
-        oIFS = "${IFS}"
-#Some sh 's can' t handle IFS = / for some reason.
-        IFS = '%' set - `echo ${dstdir} | sed - e 's@/@%@g' - e 's@^%@/@'` IFS = "${oIFS}"
+while [ $# -ne 0 ] ; do
+	pathcomp="${pathcomp}${1}"
+	shift
 
-        pathcomp =''
+	if [ ! -d "${pathcomp}" ] ;
+        then
+		$mkdirprog "${pathcomp}"
+	else
+		true
+	fi
 
-        while[$ # - ne 0];
-    do
-        pathcomp = "${pathcomp}${1}" shift
+	pathcomp="${pathcomp}/"
+done
+fi
 
-            if[! - d "${pathcomp}"];
-    then $mkdirprog "${pathcomp}" else true fi
+if [ x"$dir_arg" != x ]
+then
+	$doit $instcmd $dst &&
 
-        pathcomp = "${pathcomp}/" done fi
+	if [ x"$chowncmd" != x ]; then $doit $chowncmd $dst; else true ; fi &&
+	if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd $dst; else true ; fi &&
+	if [ x"$stripcmd" != x ]; then $doit $stripcmd $dst; else true ; fi &&
+	if [ x"$chmodcmd" != x ]; then $doit $chmodcmd $dst; else true ; fi
+else
 
-                   if[x "$dir_arg" != x] then $doit $instcmd $dst &&
+# If we're going to rename the final executable, determine the name now.
 
-                   if[x "$chowncmd" != x];
-    then $doit $chowncmd $dst;
-    else true;
-    fi&& if[x "$chgrpcmd" != x];
-    then $doit $chgrpcmd $dst;
-    else true;
-    fi&& if[x "$stripcmd" != x];
-    then $doit $stripcmd $dst;
-    else true;
-    fi&& if[x "$chmodcmd" != x];
-    then $doit $chmodcmd $dst;
-    else true;
-    fi else
+	if [ x"$transformarg" = x ] 
+	then
+		dstfile=`basename $dst`
+	else
+		dstfile=`basename $dst $transformbasename | 
+			sed $transformarg`$transformbasename
+	fi
 
-#If we're going to rename the final executable, determine the name now.
+# don't allow the sed command to completely eliminate the filename
 
-        if[x "$transformarg" = x] then dstfile =`basename
-            $dst` else dstfile =`basename $dst $transformbasename | sed $transformarg`$transformbasename fi
+	if [ x"$dstfile" = x ] 
+	then
+		dstfile=`basename $dst`
+	else
+		true
+	fi
 
-#don't allow the sed command to completely eliminate the filename
+# Make a temp file name in the proper directory.
 
-                                if[x "$dstfile" = x] then dstfile =`basename $dst` else true fi
+	dsttmp=$dstdir/#inst.$$#
 
-#Make a temp file name in the proper directory.
+# Move or copy the file name to the temp name
 
-                dsttmp = $dstdir /
-#inst.$$ #
+	$doit $instcmd $src $dsttmp &&
 
-#Move or copy the file name to the temp name
+	trap "rm -f ${dsttmp}" 0 &&
 
-                             $doit $instcmd $src $dsttmp &&
+# and set any options; do chmod last to preserve setuid bits
 
-                         trap "rm -f ${dsttmp}" 0 &&
+# If any of these fail, we abort the whole thing.  If we want to
+# ignore errors from any of these, just make sure not to ignore
+# errors from the above "$doit $instcmd $src $dsttmp" command.
 
-#and set any options; do chmod last to preserve setuid bits
+	if [ x"$chowncmd" != x ]; then $doit $chowncmd $dsttmp; else true;fi &&
+	if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd $dsttmp; else true;fi &&
+	if [ x"$stripcmd" != x ]; then $doit $stripcmd $dsttmp; else true;fi &&
+	if [ x"$chmodcmd" != x ]; then $doit $chmodcmd $dsttmp; else true;fi &&
 
-#If any of these fail, we abort the whole thing.If we want to
-#ignore errors from any of these, just make sure not to ignore
-#errors from the above "$doit $instcmd $src $dsttmp" command.
+# Now rename the file to the real destination.
 
-                         if[x "$chowncmd" != x];
-    then $doit $chowncmd $dsttmp;
-    else true;
-    fi&& if[x "$chgrpcmd" != x];
-    then $doit $chgrpcmd $dsttmp;
-    else true;
-    fi&& if[x "$stripcmd" != x];
-    then $doit $stripcmd $dsttmp;
-    else true;
-    fi&& if[x "$chmodcmd" != x];
-    then $doit $chmodcmd $dsttmp;
-    else true;
-    fi&&
+	$doit $rmcmd -f $dstdir/$dstfile &&
+	$doit $mvcmd $dsttmp $dstdir/$dstfile 
 
-#Now rename the file to the real destination.
+fi &&
 
-            $doit $rmcmd -
-        f $dstdir / $dstfile&& $doit $mvcmd $dsttmp $dstdir / $dstfile
 
-                                                                  fi&&
-
-                                                                      exit 0
+exit 0
